workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.wantedbydivers
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Set up GoogleService-Info.plist
        script: |
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist
      - name: Pod install
        script: |
          cd ios && pod install
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: Codemagic
        key_id: 9434Y4VH6U
        issuer_id: dbb08011-93cf-4501-89b0-cd49b04be3fb
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
